import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React from 'react';
import { AiOutlineMinus, AiOutlinePlus } from 'react-icons/ai';
import CartCheckout from '../../src/components/Cart/CartCheckout';
import CartProducts from '../../src/components/Cart/CartProducts';
import { Product, productsData } from '../../src/data/productsData';

interface TableHead {
  name: string;
  width: string;
}
const tableHeads: TableHead[] = [
  { name: 'Product', width: '40%' },
  { name: 'Price', width: '20%' },
  { name: 'Quantity', width: '20%' },
  { name: 'Total', width: '20%' },
];

const Cart: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>HEKTO | Get your own comfortable place</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="w-full min-h-screen py-14 flex items-center">
          <div className="w-[1024px] m-auto flex gap-8">
            <CartProducts tableHeads={tableHeads} />
            <CartCheckout />
          </div>
        </section>
      </main>
    </>
  );
};

export default Cart;
