import { GetServerSideProps, GetServerSidePropsResult, NextPage } from 'next';
import Head from 'next/head';
import { ParsedUrlQuery } from 'querystring';
import React from 'react';
import SingleBlog from '../../../src/components/SingleBlog';
import { Blog } from '../../../src/Types';

interface SingleBlogProps {
  singleBlogData: Blog;
}

interface IParams extends ParsedUrlQuery {
  id: string;
}

// get server side props function
export const getServerSideProps: GetServerSideProps<SingleBlogProps> = async (
  context
): Promise<GetServerSidePropsResult<SingleBlogProps> | any> => {
  const { id } = context.params as IParams;
  context.res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=1'
  );

  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/blogs/${id}`);
    if (!res.ok) {
      throw new Error();
    }
    const data = await res.json();

    return {
      props: {
        singleBlogData: data,
      },
    };
  } catch (err) {
    console.log(err);
  }
};

const BlogDetails: NextPage<SingleBlogProps> = ({ singleBlogData }) => {

  return (
    <>
      <Head>
        <title>HEKTO | Get your own comfortable place</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="w-full min-h-screen py-14 flex">
          <div className="w-[1024px] m-auto min-h-[32rem]">
            <SingleBlog singleBlogData={singleBlogData} />
          </div>
        </section>
      </main>
    </>
  );
};

export default BlogDetails;
