import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import DetailProduct from '../../src/components/Product/DetailProduct';
import InfoProduct from '../../src/components/Product/InfoProduct';
import RelatedProduct from '../../src/components/Product/RelatedProduct';

const ProductDetails: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>HEKTO | Get your own comfortable place</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="w-full min-h-screen py-14 m-auto flex items-center">
          <DetailProduct />
        </section>
        <InfoProduct />
        <section className="w-full min-h-[28rem] m-auto flex justify-center items-center">
          <RelatedProduct />
        </section>
      </main>
    </>
  );
};

export default ProductDetails;
