import { NextPage } from 'next';
import React from 'react';
import { useAppDispatch, useAppSelector } from '../src/Store/hooks';
import { setAuthState } from '../src/Store/slices/authState-slice';
import CoverImage from '../src/components/Authentication/CoverImage';
import Login from '../src/components/Authentication/Login';
import Register from '../src/components/Authentication/Register';
import Head from 'next/head';

const Auth: NextPage = () => {
  const dispatch = useAppDispatch();
  const authState = useAppSelector((state) => state.authState.value);

  const setCurrentPage = (state: string) => {
    dispatch(setAuthState(state));
  };

  return (
    <>
      <Head>
        <title>HEKTO | Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="w-full min-h-screen flex">
          <div className="m-auto w-[1024px] h-[32rem] flex items-stretch rounded-lg shadow-simetri relative overflow-hidden">
            <Login setCurrentPage={setCurrentPage} />
            <Register setCurrentPage={setCurrentPage} />
            <CoverImage currentPage={authState} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Auth;
