import Head from 'next/head';
import FeaturedProducts from '../src/components/Home/FeaturedProducts';
import HeroCarraousel from '../src/components/Home/HeroCarraousel';
import LeatestProducts from '../src/components/Home/LeatestProducts';
import { productsData } from '../src/data/productsData';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroCarraousel />
        <section className="w-full min-h-screen p-10 flex flex-col gap-6 items-center">
          <FeaturedProducts productsData={productsData} />
          <LeatestProducts productsData={productsData} />
        </section>
      </main>
    </>
  );
}
