import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import ProductsList from '../src/components/Shop/ProductsList';
import SideBar from '../src/components/Shop/SideBar';
import SortBar from '../src/components/Shop/SortBar';

const Shop: NextPage = () => {
  return (
    <>
      <Head>
        <title>HEKTO | Get your own comfortable place</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full px-10 py-14 flex">
        <section className="w-[1024px] px-12 m-auto">
          <SortBar />
          <section className="w-[1024px] m-auto flex justify-between min-h-[80vh]">
            <SideBar />
            <ProductsList />
          </section>
        </section>
      </main>
    </>
  );
};

export default Shop;
