import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { GiCheckMark } from 'react-icons/gi';
import { FcClock } from 'react-icons/fc';
import { FaClipboardList } from 'react-icons/fa';
import { useRouter } from 'next/router';

const OrderCompleted: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>HEKTO | Get your own comfortable place</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="w-full min-h-screen py-14 flex">
          <div className="w-[1024px] h-96 m-auto flex flex-col gap-10 px-52 py-14 items-center justify-center relative border-l-[1px] border-l-black/20 border-l-dotted border-b-[1px] border-b-black/20 border-dashed">
            <div className="p-4 rounded-full shadow-simetri flex">
              <GiCheckMark className="m-auto text-primaryPink text-4xl" />
            </div>
            <span className="text-3xl text-primaryNavyBlue font-josefin font-bold">
              Your Order Is Completed
            </span>
            <p className="text-center text-sm text-primaryBlue/40 font-lato">
              Thank you for your order! Your order is being proccessed and will
              be completed within 3-6 hours. You will receive an email
              confirmation when you order is completed
            </p>
            <button
              className="text-lg font-josefin text-primarySkyBlue py-3 px-6 bg-primaryPink border-none outline-none cursor-pointer hover:brightness-90"
              onClick={() => router.push('/shop')}
            >
              Continue Shopping
            </button>

            <div className="absolute -top-10 -left-10 flex p-1">
              <FcClock className=" text-primaryNavyBlue text-[5rem] m-auto" />
            </div>

            <div className="absolute -bottom-8 -right-10 flex p-1">
              <FaClipboardList className=" text-primaryPink text-[4rem] m-auto" />
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default OrderCompleted;
