import { NextPage } from 'next';
import Head from 'next/head';
import WishlistProducts from '../src/components/Wishlist/WishlistProducts';

const Wishlist: NextPage = () => {
  return (
    <>
      <Head>
        <title>HEKTO | Wishlist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="w-full min-h-screen py-8 flex items-center">
          <div className="w-[1024px] min-h-screen m-auto flex flex-col gap-14 items-center justify-start">
            <h1 className="text-5xl font-bold text-primaryNavyBlue">
              Wishlist
            </h1>
            <WishlistProducts />
          </div>
        </section>
      </main>
    </>
  );
};

export default Wishlist;
